# Generated by Django 5.2.10 on 2026-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_dislikes_article_likes_and_more'),
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='articles.article'),
        ),
    ]
