# Generated by Django 4.2.7 on 2026-02-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_is_active'),
    ]

    operations = [
    ]
