# Generated by Django 4.2.7 on 2026-03-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20260226_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['-created_at'], 'verbose_name': 'Magazine', 'verbose_name_plural': 'Magazines'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='magazine',
            index=models.Index(fields=['-created_at', 'is_active'], name='magazines_m_created_f29ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='magazine',
            index=models.Index(fields=['title'], name='magazines_m_title_bad3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='magazine',
            index=models.Index(fields=['slug'], name='magazines_m_slug_3637f9_idx'),
        ),
    ]
