# Generated by Django 4.2.7 on 2026-01-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160828_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('science', 'Science'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('sports', 'Sports'), ('education', 'Education')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
